
project_id = "lhlbcclbjzxkxgppmuvp"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-subscription-portal]
verify_jwt = true

[functions.update-profile-membership]
verify_jwt = true
